# zizmor configuration
# Suppressing unpinned-uses as pinning to hashes is out of scope for this lint cleanup
# and requires thorough verification of each hash.

rules:
  unpinned-uses:
    disable: true
  excessive-permissions:
    disable: true
  template-injection:
    disable: false
  cache-poisoning:
    disable: true
  archived-uses:
    disable: true
  artipacked:
    disable: true
